/*
 Oracle Infinity
 @preserve Copyright (c) 2017, 2018, 2019, Oracle and/or its affiliates. All rights reserved.
 analytics.js v1.0
 Created: 2024-08-19T06:31:25+0000

*/
(function(m,d){if(!m.ORA.analytics){var a=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_PRODUCT_READY,ORA.Event.STATUS_SUCCESS));ORA.common.TrackingPipeline.productIsReady("analytics");ORA.Debug.debug("setProductReady()","ANA")};ORA.analytics={dcsRef:null,plugins:{},addEventListener:ORA.addDOMEvent,eventQueue:null,version:{major:1,minor:0,inc:4},versionStr:"1.0.4",qryparams:{},dcsdelay:25,productReadyLatch:{},isSeedMessageTriggered:!1,elemOfEvent:function(c,b){var e=c.target||c.srcElement,
g=b||{};"string"===typeof b&&(g={},g[b.toUpperCase()]=1);for(;e&&e.tagName&&!g[e.tagName.toUpperCase()];)e=e.parentElement||e.parentNode;return e},multiTrack:function(c){try{return ORA.analytics.dcsRef.dcsMultiTrack(c),!1}catch(b){throw ORA.Debug.error("Error ORA.analytics.multiTrack: "+b.toSource(),"ANA"),b;}},instantiateExternal:function(){ORA.analytics.qryparams=ORA.common.QueryParamCache.getCache();ORA.analytics.loadJS=ORA.common.loadJS;ORA.analytics.eventQueue=new ORA.common.Queue;ORA.analytics.prettify=
ORA.common.JSONPrettify;ORA.analytics.dcsSaveCookie=ORA.common._setCookie;ORA.analytics.dcsDeleteCookie=ORA.common._deleteCookie;ORA.analytics.extendArray=ORA.common.extendArray;ORA.analytics.isFn=ORA.common.isFn;ORA.analytics.isArray=ORA.common.isArray;ORA.analytics.getCookieAsObj=ORA.common._getCookieAsObj;ORA.analytics.isEmpty=ORA.common.isEmpty;ORA.analytics.click=ORA.click;ORA.analytics.view=ORA.view;ORA.analytics.collect=ORA.collect;ORA.analytics.regPlugin=ORA.regPlugin;ORA.analytics.getTagId=
ORA.getTagId;ORA.analytics.getContextName=ORA.getContextName;ORA.analytics.getPluginsConfig=ORA.analytics._getPluginsConfig;ORA.analytics.setCookie=ORA.common._setCookie;ORA.analytics.deleteCookie=ORA.common._deleteCookie;ORA.analytics.getCookieRaw=ORA.common._getCookieRaw;ORA.analytics.getIEVer=ORA.common._getIEVer;ORA.analytics.isOptedOut=ORA.common._isOptedOut;ORA.analytics.setInfinityOptOut=ORA.common._setInfinityOptOut;ORA.analytics.addMutation=ORA.analytics.addMutation;ORA.analytics.rmMutation=
ORA.analytics.rmMutation;ORA.analytics.getFPC=function(){var c=ORA.analytics.getCookieAsObj(ORA.analytics.dcsRef.FPCConfig.name);return c&&c.id?c.id:null}},reset:function(){ORA.Debug.info("Analytics reset()","ANA");ORA.analytics.dscRef={}},execute:function(c){ORA.Debug.info("Analytics execute()","ANA");ORA.analytics.reset();var b=ORA.analyticsModule.prototype.oraConfigObj;c&&c.params&&ORA.hasVal(c.params)?(c=ORA.common.getMergedConfigs(b,c.params),ORA.analytics.setup(c)):ORA.analytics.setup(b)},performView:function(){ORA.common.clientID.isWaitForSetClientId&&
ORA.common.clientID.isClientIdSet&&(ORA.addEventHandler(ORA.Event.ANA_PRODUCT_READY,ORA.view()),ORA.common.clientID.isWaitForSetClientId=!1)},registerLoaderEvents:function(){ORA.addEventHandler(ORA.Event.LOADER_RESET,this.reset);ORA.addEventHandler(ORA.Event.LOADER_EXECUTE,this.execute);ORA.common.clientID.isClientIdSet?this.performView():ORA.addEventHandler(ORA.Event.SET_CLIENT_ID,this.performView)},setupPluginMgr:function(c){var b=ORA.analytics.getPluginCount("ora-plugins"),e=ORA.common.pluginMgr,
g=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_ORA_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("setupPluginMgr - ora Plugins Initialized, productReadyLatch.countDown()","ANA");ORA.analytics.productReadyLatch.countDown()};0<b?(ORA.Debug.debug("setupPluginMgr - ora pluginCount("+b+"), deferring initPluginsCallback until plugins loaded","ANA"),e.setNumExpectedPlugins(b),e.setInitPluginsCallback(g),e.setInjectConfigsCb(ORA.analytics._getPluginsConfig,"ora-plugins")):(0===b&&c.waitForGetClientIDCallback.apply(c)?
(ORA.Debug.debug("setupPluginMgr - ora pluginCount("+b+"), now waiting on getId, so wait to countDown latch ","ANA"),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_ORA_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS))):ORA.Debug.debug("setupPluginMgr - ora pluginCount("+b+"), not waiting on getId so countDown immediately","ANA"),g());e.setReady();ORA.fireEvent(new ORA.Event(ORA.Event.COMMON_ORA_PLUGINMGR_READY,ORA.Event.STATUS_SUCCESS));e=ORA.analytics.getPluginCount("hosted-plugins");var p=ORA.common.hostedPluginMgr,
q=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_HOSTED_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("setupPluginMgr - Hosted Plugins Initialized, productReadyLatch.countDown()","ANA");ORA.analytics.productReadyLatch.countDown()};0<e?(ORA.Debug.debug("setupPluginMgr - Hosted pluginCount("+e+"), deferring initPluginsCallback until plugins loaded","ANA"),p.setNumExpectedPlugins(e),p.setInitPluginsCallback(q),p.setInjectConfigsCb(ORA.analytics._getPluginsConfig),p.processHostedPlugins(c.config["hosted-plugins"])):
0===e&&c.waitForGetClientIDCallback.apply(c)?(ORA.Debug.debug("setupPluginMgr - hosted pluginCount("+b+"), now waiting on getId, so wait to countDown latch ","ANA"),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_HOSTED_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS)),g()):(ORA.Debug.debug("setupPluginMgr - Hosted pluginCount("+b+"), not waiting on getId so countDown immediately","ANA"),q());p.setReady();ORA.fireEvent(new ORA.Event(ORA.Event.COMMON_HOSTED_PLUGINMGR_READY,ORA.Event.STATUS_SUCCESS))},setupProductCountdownLatch:function(c){var b=
2;c.waitForGetClientIDCallback.apply(c)&&(ORA.Debug.trace("prodCountdownLatch: waitForGetIdCall, latchCount++","ANA"),b++);ORA.analytics.productReadyLatch=new ORA.common.CountDownLatchClass(b,a,"ProductReadyLatch");ORA.Debug.debug("set productReadyLatch to "+b,"ANA")},setCheckSetDisableSeed:function(c){!0===c.s_disableSeed&&ORA.common.TrackingPipeline.disableSeed()},setWaitForSetClientId:function(c){!0===c.s_waitForSetClientId&&ORA.common.clientID.waitForSetClientId()},setup:function(c){try{ORA.Debug.debug("Analytics setup() started",
"ANA");this.instantiateExternal();this.setCheckSetDisableSeed(c);this.setWaitForSetClientId(c);var b=new ORA.analytics.dcs;b.init(c);this.setupProductCountdownLatch(b);b.setup();this.dcsRef=b;this.setupPluginMgr(this.dcsRef);this.registerLoaderEvents();ORA.fireEvent(new ORA.Event(ORA.Event.ANA_SETUP_COMPLETE,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("Analytics setup() has finished","ANA")}catch(e){ORA.Debug.error("Analytics setup() failure",201,e,"ANA")}},addMutation:function(c,b,e){return ORA.common.TrackingPipeline.registerMutation(c,
b,e?e:2)},rmMutation:function(c){return ORA.common.TrackingPipeline.deregisterMutation(c)},getProductTimeout:function(){return ORA.common.TrackingPipeline.getProduct("analytics").timeout},_getPluginsConfig:function(c,b){var e={};ORA.analyticsModule.prototype.oraConfigObj[b]&&ORA.analyticsModule.prototype.oraConfigObj[b][c]&&(e=ORA.analyticsModule.prototype.oraConfigObj[b][c]);return e},getPluginCount:function(c){return ORA.analyticsModule.prototype.oraConfigObj[c]?ORA.common.extendObject(ORA.analyticsModule.prototype.oraConfigObj[c]).length():
0},getConfigParams:function(){var c=ORA.analytics,b={},e=ORA.analytics.dcsRef;e&&ORA.common.extendArray(["accountGuid","destinations","enabled","i18n","timezone"]).forEach(function(g){e[g]&&(b[g]=e[g])});b.version=c.version;b.versionStr=[b.version.major,b.version.minor,b.version.inc].join(".");b.dcsdelay=c.dcsdelay;return b},getEndPoint:function(){return"https://"+ORA.analytics.dcsRef.destinations[0].collectionServer+"/v3/"+ORA.analytics.dcsRef.destinations[0].accountGuid}};ORA.Debug.debug("ORA.analytics instantiation success",
"ANA")}})(window,window.document);
(function(m,d){ORA.analytics.dcs=function(){var a=m.RegExp?RegExp("dcs(uri)|(ref)|(aut)|(met)|(sta)|(sip)|(pro)|(byt)|(dat)|(p3p)|(cfg)|(redirect)|(cip)","i"):"";this.exre=a;this.re={};this.plugins=this.plugins={};this.trackingData=this.trackingData={};this.DCS=this.DCS={};this.destinations=[];this.DCSext=this.DCSext={};this.errors=this.errors=[];this.FPCConfig=this.FPCConfig={};this._onsitedoms=[];this.gTempWtId=this.gWtAccountRollup=this.oraId="";this.prettify=ORA.analytics.prettify;return this};
ORA.analytics.dcs.prototype={init:function(a){var c=a;try{ORA.Debug.debug("dcs init() start","ANA");"undefined"===typeof c&&(c={});this.config=c;var b=this;a=function(q,n){return c.hasOwnProperty(q)?c[q]:n};var e=function(q,n,l){return q?q.hasOwnProperty(n)?q[n]:l:l};this.extendArray=ORA.common.extendArray;this.errorlogger=function(q){ORA.Debug.error("Dcs",100,q,"ANA")};c.defaultCollectionServer||ORA.Debug.error("dcs init:  missing defaultCollectionServer");this.destinations=this.destinations=function(q){if(!q||
0===q.length)throw Error("Destinations are not configured");for(var n=[],l=0;l<q.length;l++){var v=e(q[l],"collectionServer",c.defaultCollectionServer),r={};r.collectionServer=r.collectionServer=v;r.timeout=r.timeout=e(q[l],"timeout",2E3);r.accountGuid=r.accountGuid=q[l].accountGuid;r.endpoint=r.endpoint=b.collectionEndpoint(v,q[l].accountGuid);n.push(r)}return n}(c.destinations);this.accountGuid=this.accountGuid=this.destinations[0].accountGuid;this.queue=this.queue=a("queue",[]);this.wtidTimeout=
a("wtidTimeout",1E3);this.timezone=this.timezone=a("timezone",-8);this.enabled=this.enabled=a("enabled",!0);this.i18n=this.i18n=a("i18n",!1);this.re=m.RegExp?b.i18n?{"%25":/%/g,"%26":/&/g,"%23":/#/g}:{"%25":/%/g,"%09":/\t/g,"%20":/\x20|\xA0|\x7F/g,"%23":/#/g,"%26":/&/g,"%2B":/\+/g,"%3F":/\?/g,"%5C":/\\/g,"%22":/"/g}:"";if(c.metanames){var g=c.metanames.toLowerCase();this.metanames=ORA.common.extendArray(g.split(","))}if(!0===c.metatagAuto||"true"===c.metatagAuto)this.metatagAuto=!0;this.skip_qp_no_value=
this.skip_qp_no_value=a("skip_qp_no_value",!1);this.skip_qp_no_equals=this.skip_qp_no_equals=a("skip_qp_no_equals",!1);this.skip_qp=this.skip_qp=a("skip_qp",!1);this.paidsearchparams=a("paidsearchparams","gclid");ORA.analytics.dcsdelay=c.dcsdelay||ORA.analytics.dcsdelay;this.delayAll=this.delayAll=a("delayAll",!1);this.preserve=this.preserve=a("preserve",!0);this._onsitedoms=a("onsitedoms","");ORA.common.isFn(this._onsitedoms.test)||(this._onsitedoms=ORA.common.extendArray(this._onsitedoms.toLowerCase().split(",")),
this._onsitedoms.forEach(function(q,n,l){l[n]=q.replace(/^\s*/,"").replace(/\s*$/,"")}));a("adimpressions",!1)&&(this.adclickparam=a("adsparam","WT.ac"));this.FPCConfig.enabled=this.FPCConfig.enabled=e(c.FPCConfig,"enabled",!0);this.FPCConfig.domain=this.FPCConfig.domain=e(c.FPCConfig,"domain","");this.FPCConfig.name=this.FPCConfig.name=e(c.FPCConfig,"name","ORA_FPC");this.FPCConfig.optOutCName=this.FPCConfig.optOutCName=e(c.FPCConfig,"optOutCName","Infinity.optout");this.FPCConfig.legacyCName=this.FPCConfig.legacyCName=
e(c.FPCConfig,"legacyCName","WT_FPC");this.FPCConfig.expiry=this.FPCConfig.expiry=e(c.FPCConfig,"expires",63113851500);63113851500<this.FPCConfig.expiry&&(this.FPCConfig.expiry=63113851500);this.FPCConfig.expireDate=new Date(this.getTime()+this.FPCConfig.expiry);this.FPCConfig.sessionOnly=0===this.FPCConfig.expiry||e(c.FPCConfig,"sessionOnly",!1);this.FPCConfig.autoTLD=this.FPCConfig.autoTLD=e(c.FPCConfig,"autoTLD",!1);c.cookieTypes&&(this.FPCConfig.enabled="none"!==c.cookieTypes.toLowerCase());var p=
{DNTBehavior:ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT",wtidTimeout:this.wtidTimeout,cookie:{enable:this.FPCConfig.enabled,name:this.FPCConfig.name,expires:this.FPCConfig.expiry,autoTLD:this.FPCConfig.autoTLD,sessionOnly:this.FPCConfig.sessionOnly,expireDate:this.FPCConfig.expireDate,domain:this.FPCConfig.domain},endpoint:{clientIDServer:this.destinations[0].collectionServer,accountGuid:this.destinations[0].accountGuid,protocol:"https"}};ORA.common.clientID.clientId=
this.dcsGetFPC().id||null;ORA.common.clientID.setConfig(p);this.plugins=c.plugins||{};ORA.analytics.dcs.prototype.action_collect=ORA.analytics.dcs.prototype.action_collect;ORA.analytics.dcs.prototype.init=ORA.analytics.dcs.prototype.init;ORA.analytics.dcs.prototype.setup=ORA.analytics.dcs.prototype.setup;ORA.analytics.dcs.prototype.dcsGetFPC=ORA.analytics.dcs.prototype.dcsGetFPC;ORA.analytics.dcs.prototype.dcsGetCookie=ORA.analytics.dcs.prototype.dcsGetCookie;ORA.analytics.dcs.prototype.dcsNavigation=
ORA.analytics.dcs.prototype.dcsNavigation;this.registerProtocol();ORA.Debug.debug("dcs init() finish","ANA");return this}catch(q){throw ORA.Debug.error("Error in init() - "+q.toString()),q;}},registerProtocol:function(){var a=ORA.common.TrackingPipeline;null===a.getCommProtocol(ORA.common.CommManager.GIF)&&(ORA.common._analyticsProtocol=ORA.common.protocols.gifProtocol,a.setCommProtocol(ORA.common.CommManager.GIF,ORA.common._analyticsProtocol))},collectionEndpoint:function(a,c,b){a||ORA.Debug.debug("Warning:  missing collectServer");
a=a?a:"";if(!c)throw Error("accountGuid must be configured for "+a);return"https://"+a+"/"+c+"/"+(b?b:"dcs.gif")},setReady:function(){ORA.Debug.debug("setReady()","ANA");this._readySet||(this.flushqueue(),this.redirectqueue(),this._readySet=!0)},flushqueue:function(){ORA.Debug.trace("flushqueue()","ANA");for(var a=0;a<this.queue.length;a++)this.doAction(this.queue[a]);this.queue=[]},redirectqueue:function(){var a=this;this.queue.push=function(c){a.doAction(c)}},dcsGetCookie:function(a){return ORA.analytics.dcsGetCookie(a,
this.FPCConfig.name)},dcsIsFpcSet:function(a,c){var b=ORA.analytics.getCookieAsObj,e=ORA.analytics.isEmpty;b=b(a);this.gTempWtId=b.id;return e(b)?2:c===b.id?0:3},dcsGetFPC:function(){return ORA.analytics.getCookieAsObj(this.FPCConfig.name)},dcsFPC:function(){var a=ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT";if(!ORA.analytics.isOptedOut())if(this.FPCConfig.enabled){this.trackingData.ce="1";var c=this.trackingData,b=this.FPCConfig.name,e=new Date,g=6E4*e.getTimezoneOffset()+
36E5*this.timezone;e.setTime(e.getTime()+g);var p=new Date(e.getTime());c.co_f="";c.vtvs=c.vt_f="";var q=ORA.analytics.getCookieAsObj(b);g=function(l){var v=q.id;null!==v&&(c.co_f=v,e.getTime()>p.getTime()+288E5&&p.setTime(e.getTime()),"undefined"===typeof l.gTempWtId||l.gTempWtId!==v)&&(c.vt_f="1",l.gTempWtId=v)};if(!ORA.common._isDNTSet()||"honorDNT"!==a){g(this);c.co_f=escape(c.co_f);q.id=c.co_f;this.FPCConfig.sessionOnly?ORA.common.mobile.nativeAppCkSend({name:b,value:q,domain:this.FPCConfig.domain,
date:this.FPCConfig.expireDate,path:"/",type:"session",timeout:this.FPCConfig.expiry}):ORA.common.mobile.nativeAppCkSend({name:b,value:q,domain:this.FPCConfig.domain,date:this.FPCConfig.expireDate,path:"/",type:"persisted",timeout:this.FPCConfig.expiry});a=ORA.common.isFpcSet(b,c.co_f);0!==a&&(c.co_f="",c.vt_f=a);var n={};ORA.common.extendObject(c).forEach(function(l,v){null!==l&&""!==l&&(n["WT."+v]=l)});return n}}else this.trackingData.ce="0"},dcsGetIdCallback:function(a){"undefined"!==typeof a&&
(this.oraId||(this.oraId=a),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_AFTER_GETID,ORA.Event.STATUS_SUCCESS)));this.setReady();ORA.analytics.productReadyLatch.countDown()},waitForGetClientIDCallback:function(){var a=ORA.common._getCookieAsObj(),c=2!==this.dcsIsFpcSet(this.FPCConfig.name),b=ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT";b=ORA.common._isDNTSet()&&"honorDNT"===b;return ORA.common._isOptedOut(a)||c||!this.FPCConfig.enabled||b||ORA.common._getConfigObject().s_waitForSetClientId?
!1:!0},setup:function(){try{var a=this,c=function(b){a.dcsGetIdCallback.apply(a,[b])};this.FPCConfig.enabled?ORA.common.mobile.delay(function(){a.waitForGetClientIDCallback.apply(a)?ORA.common.clientID.getClientID(c):(ORA.common.clientID.getId(ORA.common.clientID.cfg.endpoint,null),a.setReady.apply(a,[]))},"ANA",ORA.analyticsModule.prototype.oraConfigObj):this.setReady();this.enQueue("collect",{element:void 0,event:void 0});ORA.fireEvent(new ORA.Event(ORA.Event.ANA_DCS_SETUP,ORA.Event.STATUS_SUCCESS));
ORA.addEventHandler(ORA.Event.SET_CLIENT_ID,function(b){a.oraId=b.params},null,!0);ORA.addEventHandler(ORA.Event.CLEAR_CLIENT_ID,function(){ORA.analytics.pageAnalysis["WT.co_f"]=null},null,!0);return this}catch(b){this.errors.push(b),this.errorlogger(b)}},addQueryParameters:function(a,c){var b=this.DCS;if(0<a.length()&&!this.skip_qp){a.forEach(function(p,q){var n=p;if(!((this.skip_qp_no_value||this.skip_qp_no_equals)&&"undefined"===typeof p||this.skip_qp_no_equals&&""===p)){if("undefined"===typeof p||
null===p)n="undefined";b[q]=n}},this);var e=this.paidsearchparams.length?this.paidsearchparams.toLowerCase().split(","):[];for(var g=0;g<e.length;g++)if(ORA.common.QueryParamCache.contains(e[g],!0)){c.srch="1";break}}},dcsVar:function(){var a=this.trackingData;this.i18n&&(a.le="string"===typeof d.defaultCharset?d.defaultCharset:"string"===typeof d.characterSet?d.characterSet:"unknown");a.tv=ORA.analytics.versionStr;var c=ORA.common.QueryParamCache.getCache();this.addQueryParameters(c,a);!0===this.metatagAuto&&
ORA.common.visitMetaTags(this.dcsMetaTagsAutoScrape,d,this.DCSext);this.metanames&&ORA.common.visitMetaTags(this.dcsMetaTagArrScrape(this.metanames),d,this.DCSext)},dcsMetaTagArrScrape:function(a){return function(c,b,e){c=c.toLowerCase();-1!==a.indexOf(c)&&(e["meta_"+c]=b)}},dcsMetaTagsAutoScrape:function(a,c,b){0===a.indexOf("ORA.")?b[a]=c:0===a.indexOf("DCS.")?(a=a.split("DCS."),a[1]&&(b[a[1]]=c)):0===a.indexOf("DCSext.")&&(a=a.split("DCSext."),a[1]&&(b[a[1]]=c))},getPageAnalysis:function(){var a=
ORA.analytics.dcsRef.dcsFPC(),c=ORA.common.extendArray;ORA.analytics.pageAnalysis?c(["vt_f"]).forEach(function(b){ORA.analytics.pageAnalysis["WT."+b]&&delete ORA.analytics.pageAnalysis["WT."+b]}):ORA.analytics.pageAnalysis=ORA.analytics.dcsRef.genPageAnalysis();return ORA.paramsMerge(ORA.analytics.pageAnalysis,a)},genPageAnalysis:function(){try{if(ORA.fireEvent(new ORA.Event(ORA.Event.ANA_BEFORE_PAGE_ANALYSIS,ORA.Event.STATUS_SUCCESS)),!ORA.analytics.isOptedOut()){var a=this.trackingData,c=this.DCS,
b=this.DCSext,e=this.i18n;e&&(a.dep="");var g={},p;for(p in c)c.hasOwnProperty(p)&&void 0!==c[p]&&"function"!==typeof c[p]&&(g[p]=c[p]);for(var q in a)a.hasOwnProperty(q)&&""!==a[q]&&void 0!==a[q]&&"function"!==typeof a[q]&&(g["WT."+q]=a[q]);for(var n in b)b.hasOwnProperty(n)&&""!==b[n]&&void 0!==b[n]&&"function"!==typeof b[n]&&(e&&(a.dep=0===a.dep.length?n:a.dep+";"+n),g[n]=b[n]);e&&0<a.dep.length&&(g["WT.dep"]=a.dep);ORA.Debug.superfine("pageAnalysis: "+this.prettify(g),"ANA");ORA.fireEvent(new ORA.Event(ORA.Event.ANA_AFTER_PAGE_ANALYSIS,
ORA.Event.STATUS_SUCCESS));return g}}catch(l){ORA.Debug.error("error in pageAnalyze: "+l.toString())}},doRequest:function(){var a=this.destinations,c=this.getPageAnalysis;ORA.common.TrackingPipeline.registerMutation("analyticsAnnotate",function(b){if(b.params.mutation&&(!0===b.params.mutation.pageview||!0===b.params.mutation.conversion||!0===b.params.mutation.click||!0===b.params.mutation.collect&&!1!==b.params.sendSessionInfo||!0===b.params.mutation.view)){var e=c(),g;for(g in e)e.hasOwnProperty(g)&&
!b.getParam(g)&&b.setParam(g,e[g]);b.setParam("ora.tag_id",ORA.getTagId());b.setParam("ora.tag_config",ORA.getContextName());ORA.Debug.debug(b.params.desc?"annotating "+b.params.desc+" w/ analytics page analysis":"annotating w/ analytics page analysis","ANA");ORA.Debug.trace("annotating payload w/ "+ORA.analytics.prettify(e),"ANA");ORA.Debug.trace("Endpoints: "+ORA.analytics.prettify(a),"ANA");if("collect"!==b.params.desc)for(e=0;e<a.length;e++)b.endpoints.push({endpoint:a[e].endpoint,timeout:a[e].timeout,
conf:ORA.analytics.dcsRef,protocolType:ORA.common.CommManager.GIF});ORA.fireEvent(new ORA.Event(ORA.Event.ANA_PV_MUTATE,ORA.Event.STATUS_SUCCESS))}},1);ORA.Debug.debug("doRequest() - register mutation","ANA")},pageAnalyze:function(){ORA.Debug.trace("pageAnalyze()");this.dcsVar();this.adclickparam&&0<this.adclickparam.length&&this.dcsAdSearch();this.pageAnalyzehasRun=!0},getTime:function(){return(new Date).getTime()},dumpCounter:0,spinLock:function(a){for(var c=this.getTime();this.getTime()-c<a;)this.dumpCounter++},
enQueue:function(a,c){var b=a;ORA.Debug.debug("enQueue() - action: "+JSON.stringify(b)+" msg: "+JSON.stringify(c),"ANA");b||(b="collect");this.queue.push({action:b,message:c})},doAction:function(a){ORA.Debug.debug("doAction() - cmd: "+this.prettify(a),"ANA");var c="action_"+a.action;a=a.message;this.pageAnalyzehasRun||this.pageAnalyze();a.event&&!a.element&&(a.element=ORA.analytics.elemOfEvent(a.event,{A:1}));if(ORA.analytics.isFn(this[c]))this[c](a)},action_collect:function(a){ORA.Debug.debug("action_collect()",
"ANA");this.doRequest(a)},dcsIsOnsite:function(a,c){var b=a;if(0<b.length){b=b.toLowerCase();if(b===window.location.hostname.toLowerCase())return!0;if(ORA.analytics.isFn(c.test))return c.test(b);if(0<c.length)for(var e=c.length,g=0;g<e;g++)if(b===c[g])return!0}return!1},dcsNavigation:function(a,c){var b="",e="",g=c.length,p;for(p=0;p<g;p++){var q=c[p];if(q.length&&(e=ORA.analytics.elemOfEvent(a,q),b=e.getAttribute&&e.getAttribute("id")?e.getAttribute("id"):"",e=e.className||"",b.length||e.length))break}return b.length?
b:e},dcsAdSearch:function(){if(d.links){var a=this.adclickparam+"\x3d",c=a.length;a=new RegExp(a,"i");var b=d.links.length,e=d.URL+"",g=e.search(a);if(-1!==g){var p=e.indexOf("\x26",g);var q=-1!==p?e.substring(g,p):e.substring(g,e.length);var n=new RegExp(q+"(\x26|#)","i")}for(e=0;e<b;e++)if(d.links[e].href){var l=d.links[e].href+"";q&&0<q.length&&(l=l.replace(n,"$1"));p=l.search(a);-1!==p&&(g=p+c,p=l.indexOf("\x26",g),p=-1!==p?l.substring(g,p):l.substring(g,l.length),this.trackingData.ad=this.trackingData.ad?
this.trackingData.ad+";"+p:p)}}}};ORA.Debug.debug("dcs class loaded","ANA")})(window,window.document);
(function(m,d,a){ORA.analytics.find=function(c){ORA.analytics.selectorEngine||(ORA.analytics.selectorEngine=ORA.analytics.findSelector());return ORA.analytics.selectorEngine(c)};ORA.analytics.findSelector=function(){var c=/MSIE (\d+)/.exec(a.userAgent);c=c?c[1]:99;var b=d.body;if(d.querySelectorAll&&b&&8<c)return function(e){return b.querySelectorAll(e)};if(m.jQuery)return m.jQuery.find;if(m.Sizzle)return m.Sizzle;if(m.YAHOO&&YAHOO.util&&YAHOO.util.Selector)return YAHOO.util.Selector.query;if("qwery"in
m)return qwery;m.YUI&&YUI().use("node",function(e){return e.all});return d.querySelectorAll&&b?function(e){return b.querySelectorAll(e)}:function(){return[]}};ORA.Debug.debug("selectorEngine initialized","ANA")})(window,window.document,window.navigator);
(function(){var m={cfg:{standardEvents:{download:!1,offsite:!1,onsite:!1,rightclick:!1,anchor:!1,javascript:!1,scrollTracking:!1},scroll_frequency:25,eventList:{},downloadtypes:"xls,doc,pdf,txt,csv,zip,docx,xlsx,rar,gzip",socialTypes:{},trackSocial:!0},init:function(d,a){var c=d.config||{},b=a||function(){};ORA.Debug.debug("Event Track plugin Start Init","ANA-ET");try{for(var e in c)c.hasOwnProperty(e)&&(m.cfg[e]=c[e]);if(void 0!==m.cfg.enable&&!m.cfg.enable)return ORA.Debug.debug("Event Track plugin is disabled - exiting",
"ANA-ET"),b();var g=ORA.getIEVer();if(g&&9>g)return ORA.Debug.info("requires \x3e\x3d ie9, disabling plugin","ANA-ET"),b();ORA.Debug.info("Adding standard events","ANA-ET");m._addStandardEvents();if(!document.querySelectorAll)return ORA.Debug.info("Event Track plugin requires querySelectorAll function","ANA-ET"),b(),!1;m._addMatches();ORA.Debug.info("Binding to objects","ANA-ET");m._bind()}catch(p){ORA.Debug.error("Event Track plugin Init Error"+p.message,"ANA-ET"),b()}b();ORA.Debug.debug("Event Track plugin Start Init Complete",
"ANA-ET")},_getFullUrl:function(d){if("A"===d.nodeName){var a=d.cloneNode(!0);a.href=d.href;return a}return d},_eventCallback:function(d,a){try{for(var c=d.eventTrigger&&d.eventTrigger.split(" ")||["mousedown"],b=function(g,p,q){q._evtMsg(g);try{var n=q._fnCreator(d.eventCallback)(g,p);q._isEmptyObj(n)||(ORA.collect({config:{endpoints:[{endpoint:ORA.analytics.getEndPoint(),protocolType:"beaconProtocol"}],applyMutations:!0},data:n.data}),q._fnCreator(d.fnFinishCallback)(g))}catch(l){ORA.Debug.error("Event Track error in event callback: "+
l.message,"ANA-ET")}},e=0;e<c.length;e++)"immediate"!==c[e].toLowerCase()?(ORA.Debug.info("Event Track for "+a+" bind to "+d.selector+" event: "+c[e],"ANA"),this._delegate(document,c[e].toLowerCase(),d.selector,b,d,this)):(ORA.Debug.info("Event Track Immediate: "+a,"ANA"),b(null,null,this))}catch(g){ORA.Debug.error("Error binding adding selector for: "+a+" err: "+g.message,"ANA-ET")}},_delegate:function(d,a,c,b,e,g){function p(n){return function(l,v,r){var u=l.target||l.srcElement,k=u;"scroll"===
l.type&&b.call(null,l,v,r);for("A"===u.nodeName&&u.href&&(k=m._getFullUrl(u));k&&k!==document;)k.matches(c)&&b.call(k,l,v,r),k=k.parentNode}.apply(this,[n,e,g])}if(d.addEventListener)d.addEventListener(a,function(n){p(n)});else{var q=a;"click"===a&&(q="mousedown");d.attachEvent("on"+q,function(n){p(n)})}},_bind:function(){var d=this.cfg.eventList,a;for(a in d)d.hasOwnProperty(a)&&this._eventCallback(d[a],a)},_evtMsg:function(d){if(d){var a="Event Triggered:"+d.type+" node:"+(d.srcElement||d.target).nodeName+
" #";a+=(d.srcElement||d.target).id+" class:"+(d.srcElement||d.target).className;ORA.Debug.info(a,"ANA-ET")}else ORA.Debug.info("Event Triggered for immediate event","ANA-ET")},_fnCreator:function(d){return"string"===typeof d?new Function("e",d):"function"===typeof d?d:function(){}},_addMatches:function(){Element.prototype.matches||(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.msMatchesSelector||
Element.prototype.oMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.webkitMatchesSelector||function(d){d=(this.document||this.ownerDocument).querySelectorAll(d);var a=d.length;for(--a;0<=a&&d.item(a)!==this;)--a;return-1<a})},_isRightClick:function(d){d=d||window.event;if(d.which)d=3===d.which;else if(d.button)d=2===d.button;else return!1;return d},_getHrefInfo:function(d){d=d.target||d.srcElement||{};var a={},c=d,b=document.createElement("a");d=this._findA(d);
if(!d.href)return{};b.href=d.href;a.dcssip=b.hostname?b.hostname.split(":")[0]:window.location.hostname;b.pathname&&0!==b.pathname.indexOf("/")?a.dcsuri="/"+b.pathname:a.dcsuri=b.pathname?b.pathname:"/";b.search&&(a.dcsqry=b.search.substring(b.search.indexOf("?")+1,b.search.length));a.dcsref=document.referrer;a["WT.nv"]=ORA.common.getObjId(c);a["WT.dl"]="24";return this._cleanPayload(a)},_cleanPayload:function(d){for(var a in d)d.hasOwnProperty(a)&&!d[a]&&delete d[a];return d},_findA:function(d){for(;d&&
"A"!==d.nodeName;)d=d.parentNode;return d},_checkOnsiteDom:function(d,a){var c=ORA.analytics.dcsRef._onsitedoms;c.test||(1===c.length&&""===c[0]&&(c=[location.host.split(":")[0]]),c=new RegExp(c.join(",").toLowerCase().replace(",","|").replace(/^\s*/,"").replace(/\s*$/,"")));return!(m._isRightClick(a)||!c.test(d.hostname))},_isEmptyObj:function(d){if("object"!==typeof d)return!0;for(var a in d)if(d.hasOwnProperty(a))return!1;return!0},_addStandardEvents:function(){var d={download:"_addDownloadTracking",
offsite:"_addOffsiteTracking",onsite:"_addOnsiteLinkTracking",anchor:"_addAnchorTracking",rightclick:"_addRightClickTracking",javascript:"_addJavaScriptTracking",scrollTracking:"_addScrollTracking"},a;for(a in this.cfg.standardEvents)if(this.cfg.standardEvents.hasOwnProperty(a)&&this.cfg.standardEvents[a])this[d[a]]()},_addDownloadTracking:function(){ORA.Debug.info("Event Track plugin Add download tracking","ANA-ET");for(var d=[],a=m.cfg.downloadtypes.toLowerCase().split(","),c=0;c<a.length;c++)d.push('A[href*\x3d".'+
a[c]+'" i]');m.cfg.eventList.download={eventTrigger:"click",selector:d.join(","),eventCallback:function(b){var e=b.target||b.srcElement||b.target||{},g=m._getHrefInfo(b);ORA.Debug.debug("Download Callback Called");if(m._isRightClick(b)||!g)return{};g["WT.ti"]="Download:"+e.textContent||e.innerText;g["WT.dl"]="20";return{data:g}}}},testSocial:function(d,a,c){for(var b=0;b<d[a].length;b++)if(-1<c.toLowerCase().indexOf(d[a][b].toLowerCase()))return!0;return!1},isSocial:function(d){var a=m.cfg.socialTypes,
c;for(c in a)if(a.hasOwnProperty(c)&&m.testSocial(a,c,d))return c;return null},_addOnsiteLinkTracking:function(){ORA.Debug.info("Event Track plugin add onsite link tracking","ANA-ET");for(var d=m.cfg.downloadtypes.toLowerCase().split(","),a=':not([href*\x3d"javascript:"])',c=0;c<d.length;c++)a+=':not([href*\x3d".'+d[c]+'" i])';d=['A:not([href^\x3d"//"])'+a];c=[location.hostname];ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&(c=ORA.analytics.dcsRef._onsitedoms);if(!c.test){if(""===c||0===
c[0].length)c=[location.hostname];for(var b=0;b<c.length;b++)d.push('A[href*\x3d"'+c[b]+'"]'+a)}m.cfg.eventList.onsite={eventTrigger:"click",selector:d.join(","),eventCallback:function(e){var g=e.target||e.srcElement||{},p=m._getHrefInfo(e);ORA.Debug.debug("Onsite Link Callback Called");if(m._isEmptyObj(p))return{};for(;g&&"A"!==g.nodeName;)g=g.parentNode;if(!m._checkOnsiteDom(g,e))return ORA.Debug.debug("Onsite Link Callback Called - fails onsite test. Exiting"),{};p["WT.ti"]="Onsite:"+p.dcssip+
p.dcsuri;p.dcsqry&&(p["WT.ti"]+=p.dcsqry);p["WT.dl"]="1";return{data:p}}}},_addOffsiteTracking:function(){ORA.Debug.info("Event Track plugin add offsite tracking","ANA-ET");var d=['A:not(A[href*\x3d"javascript:"])'],a=[location.hostname];ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&(a=ORA.analytics.dcsRef._onsitedoms);if(!a.test){d=[];""===a&&(a=[location.host]);for(var c=0;c<a.length;c++)d.push('A:not([href*\x3d"'+a[c]+'"]):not([href*\x3d"javascript:"])')}m.cfg.eventList.offsite={eventTrigger:"click",
selector:d.join(","),eventCallback:function(b){var e=b.target||b.srcElement||{},g=m._getHrefInfo(b);ORA.Debug.debug("Offsite Callback Called");if(m._isEmptyObj(g))return{};for(;e&&"A"!==e.nodeName;)e=e.parentNode;var p=m.isSocial(e.href);p&&m.cfg.trackSocial&&(g["WT.soc_action"]=p+":click");if(m._checkOnsiteDom(e,b))return ORA.Debug.debug("Offsite Callback Called - fails offsite test exiting"),{};g["WT.ti"]="Offsite:"+g.dcssip+g.dcsuri;g.dcsqry&&(g["WT.ti"]+=g.dcsqry);g["WT.dl"]="24";return{data:g}}}},
_addRightClickTracking:function(){ORA.Debug.info("Event Track plugin add right click tracking","ANA-ET");for(var d=[],a=m.cfg.downloadtypes.toLowerCase().split(","),c=0;c<a.length;c++)d.push('A[href*\x3d".'+a[c]+'" i]');m.cfg.eventList.rightClick={eventTrigger:"mousedown",selector:d.join(","),eventCallback:function(b){ORA.Debug.debug("Rightclick Callback Called");if(!m._isRightClick(b)&&!m.cfg.testRightClick)return ORA.Debug.debug("RightClick Callback Called - exiting fails rightclick test"),{};var e=
b.element||b.srcElement||b.target||{};b=m._getHrefInfo(b);if(!b)return{};b["WT.ti"]="RightClick:"+e.textContent||e.innerText;b["WT.dl"]="25";return{data:b}}}},_addJavaScriptTracking:function(){ORA.Debug.info("Event Track plugin add javascript tracking","ANA-ET");m.cfg.eventList.javaScript={eventTrigger:"click",selector:'A[href*\x3d"javascript:"]',eventCallback:function(d){var a=d.element||d.srcElement||d.target||{};d=m._getHrefInfo(d);if(m._isEmptyObj(d))return{};ORA.Debug.debug("JavaScript Callback Called");
d["WT.ti"]=a.innerHTML?"JavaScript:"+a.innerHTML:"JavaScript:";d["WT.dl"]="22";d.dcssip=window.location.hostname;d.dcsuri=a.href;return{data:d}}}},_addAnchorTracking:function(){ORA.Debug.info("Event Track plugin add anchor tracking","ANA-ET");var d=window.location.pathname.split("/").pop();m.cfg.eventList.anchorTracking={eventTrigger:"click",selector:'A[href^\x3d"#"],A[href*\x3d"'+d+'#"]',eventCallback:function(a,c){var b=a.target||a.srcElement||{},e=m._getHrefInfo(a);if(m._isEmptyObj(e))return{};
for(ORA.Debug.debug("Anchor Callback Called");b&&"A"!==b.nodeName;)b=b.parentNode;if(!m._checkOnsiteDom(b,a)||!c.hasHash(b))return ORA.Debug.debug("Anchor Callback Called - no Hash address found, or offsite link - exiting hash:"+b.hash,"ANA-ET"),{};e["WT.ti"]="Anchor:"+(b.hash||"#");e["WT.dl"]="21";c.checkFragment(b);return{data:e}},hasHash:function(a){return a.hash&&-1<a.hash.indexOf("#")},checkFragment:function(a){ORA.analytics.plugins&&ORA.analytics.plugins.fragment&&ORA.analytics.plugins.fragment.updateFragData&&
ORA.analytics.plugins.fragment.updateFragData(a.hash)}}},_isMissingSent:!1,_getScrollPayload:function(d,a){return{"WT.page_scroll_depth":100<d*a?100:d*a,"WT.dl":"71"}},_addScrollTracking:function(){ORA.Debug.info("Event Track plugin add anchor tracking","ANA-ET");m.cfg.eventList.scrollTracking={selector:"",eventTrigger:"scroll",eventCallback:function(){var d=m.cfg.scroll_frequency,a=ORA.common.scrollEventCallback(d);window.evtScrollTracker||(window.evtScrollTracker={});if(!window.evtScrollTracker[a]){window.evtScrollTracker[a]=
!0;if(!m._isMissingSent){m._isMissingSent=!0;for(var c=1;c<a;c++)window.evtScrollTracker.hasOwnProperty(c)||(window.evtScrollTracker[c]=!0,ORA.collect({config:{endpoints:[{endpoint:ORA.analytics.getEndPoint(),protocolType:"beaconProtocol"}],applyMutations:!0},data:m._getScrollPayload(c,d)}))}return{data:m._getScrollPayload(a,d)}}return{}}}},addTracking:function(d,a){"object"===typeof d&&"string"===typeof a?m._eventCallback(d,a):ORA.Debug.debug("Ignoring addTrack call - obj or trigger type error",
"ANA-ET")}};ORA.regPlugin("evtTrack",m.init);ORA.analytics.plugins.evtTrack||(ORA.analytics.plugins.evtTrack={});ORA.analytics.plugins.evtTrack.addTracking=m.addTracking;ORA.analytics.plugins.evtTrack.eventTrack=m})();
(function(){function m(){if(this.href){var f=this.href;if(k.hasOwnProperty("addHash")||k.hasOwnProperty("addParam")||k.hasOwnProperty("autoSelect")){var h=f;if(k.autoSelect||k.addHash)h=d(h);if(k.autoSelect&&h===f||!k.autoSelect&&k.addParam)h=a(h);f=h}else if("parameter"!==k.addIdTreatment&&(f=d(this.href)),"auto"===k.addIdTreatment&&f===this.href||"parameter"===k.addIdTreatment)f=a(this.href);this.href=f}}function d(f){var h=r()||{};if(f&&-1<f.indexOf("#")||!h.id||!k.guard)return f;k.encode&&window.btoa&&
(h.id=btoa(h.id));ORA.Debug.debug("Adding hash to href: "+f+"#xd_co_f\x3d"+h.id+k.guard,"crossDomain-ANA");return f+"#xd_co_f\x3d"+h.id+k.guard}function a(f){var h=r();if(!f||h&&!h.id||!k.guard)return f;k.encode&&window.btoa&&(h.id=btoa(h.id));ORA.Debug.debug("Adding parameters to href: "+f+"?xd_co_f\x3d"+h.id+k.guard,"crossDomain-ANA");a:{h="xd_co_f\x3d"+h.id;var t=f.replace(RegExp("(\x26|\\?)xd_co_f\x3d[^\x26|#]*"),"$1"+h);if(f&&-1===f.indexOf("xd_co_f\x3d"))if(-1!==f.indexOf("?")){f=-1!==f.indexOf("#")?
-1!==f.split("#")[0].indexOf("?")?f.split("?")[0]+"?"+h+"\x26"+f.split("?")[1]:f.split("#")[0]+"?"+h+"#"+f.split("#")[1]:f.split("?")[0]+"?"+h+"\x26"+f.split("?")[1];break a}else t=-1!==f.indexOf("#")?f.split("#")[0]+"?"+h+"#"+f.split("#")[1]:f+"?"+h;f=t}return f}function c(f){var h=/[^A-Z0-9+\/=]/i,t=f.length;if(!t||0!==t%4||h.test(f))return!1;h=f.indexOf("\x3d");return-1===h||h===t-1||h===t-2&&"\x3d"===f[t-1]}function b(f,h){var t=f.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]"),w;(t=(new RegExp("[\\?\x26]"+
t+"\x3d([^\x26#]*)")).exec(h||location.search))&&(w=decodeURIComponent(t[1].replace(/\+/g," ")))&&c(w)&&window.atob&&(w=atob(w));return w}function e(f,h){var t,w=f.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");(w=(new RegExp("[#]"+w+"\x3d(.*)"+k.guard)).exec(h||location.hash))&&(t=decodeURIComponent(w[1].replace(/\+/g," ")))&&c(t)&&window.atob&&(t=atob(t));return t}function g(f,h,t,w){function y(C){return function(D){for(var B=D.target;B&&B!==document;){var A=B;if("A"===A.nodeName){var E=A.cloneNode(!0);
E.href=A.href;A=E}if(!A.matches)break;if(A.matches(h))break;if(A.matches(f)){w.call(B,D);break}B=B.parentNode}}.apply(this,[C])}if(document.addEventListener)document.addEventListener(t,y);else{var z=t;"click"===t&&(z="mousedown");document.attachEvent("on"+z,y)}}function p(f){if(u&&f.payload["wt.co_f"]!==u){ORA.Debug.debug("Resessionizing from "+f.payload["wt.co_f"]+"to"+u,"crossDomain-ANA");f.payload["wt.co_f"]=u;f=r();f.id=u;var h=ORA.analytics.dcsRef,t=h.FPCConfig.expireDate||new Date((new Date).getTime()+
63113851500),w="";h.FPCConfig.sessionOnly||(w="; expires\x3d"+t.toGMTString());ORA.analytics.setCookie(h.FPCConfig.name||"ORA_FPC",{id:f.id},""===h.FPCConfig.domain?w+"; path\x3d/":w+"; path\x3d/; domain\x3d"+h.FPCConfig.domain)}ORA.analytics.rmMutation("crossDomain")}function q(f){for(var h in f)f.hasOwnProperty(h)&&(k[h]=f[h]);return k}function n(f){var h=[location.hostname],t=['A[href*\x3d"'+location.hostname+'"]'];!k.ignoreOnsiteDoms&&ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&!h.test&&
""!==ORA.analytics.dcsRef._onsitedoms[0]&&(h=ORA.analytics.dcsRef._onsitedoms);if(h.test)ORA.Debug.debug("crossDomain does not support using regex for onsitedom list - using localhost","crossDomain-ANA");else{t=[];""===h&&(h=[location.host]);for(var w=0;w<h.length;w++)t.push('A[href*\x3d"'+h[w]+'/"]')}t.push('A[href*\x3d"javascript:"],A[href*\x3d"mailto:"],A[href*\x3d"tel:"],A[href*\x3d"sms:"]');h=t.join(",");"localhost"!==f&&(h=h.concat(",",f));ORA.Debug.debug("CrossDomain using deny list: "+h,"crossDomain-ANA");
return h}function l(){Element.prototype.matches||(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.webkitMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector||function(f){f=(this.document||this.ownerDocument).querySelectorAll(f);var h=f.length;for(--h;0<=h&&f.item(h)!==this;)--h;return-1<h})}
function v(){if(!k.enable)return ORA.Debug.info("crossDomain Plugin is disabled","crossDomain-ANA"),!0;if(k.hasOwnProperty("addHash")||k.hasOwnProperty("addParam")||k.hasOwnProperty("autoSelect")){if(!(k.autoSelect||k.addHash||k.addParam))return ORA.Debug.info("Plugin config invalid: Must specify at least one way of adding visitor`s ID","crossDomain-ANA"),!0}else if("auto"!==k.addIdTreatment&&"hash"!==k.addIdTreatment&&"parameter"!==k.addIdTreatment)return ORA.Debug.info("Plugin config invalid: Must specify at least one way of adding visitor`s ID",
"crossDomain-ANA"),!0;var f=ORA.getIEVer();return f&&9>f?(ORA.Debug.info("Browser is not compatible, requires IE9+","crossDomain-ANA"),!0):!1}function r(){var f=ORA.analytics.dcsRef,h="ORA_FPC";f&&f.FPCConfig&&f.FPCConfig.name&&(h=f.FPCConfig.name);var t={};f=RegExp(""+h+"[^;]+").exec(document.cookie)||"";f=decodeURIComponent(f.toString().replace(/^[^=]+./,""));try{f&&f.split(":").forEach(function(w){t[w.split("\x3d")[0]]=w.split("\x3d")[1]})}catch(w){return null}return t}var u,k={enable:!0,guard:"~",
addIdTreatment:"auto",encode:!0,denyListSelector:"localhost",allowListSelector:"A",testSessionId:!1,ignoreOnsiteDoms:!1},x=function(){var f=document.createElement("br");return function(h){try{f.querySelector(h)}catch(t){return!1}return!0}}();ORA.Debug.info("crossDomain plugin Register (blocking)","crossDomain-ANA");ORA.regPlugin("crossDomain",function(f,h){var t=h||function(){},w=f.config;l();try{q(w);if(v())return t();var y=k.hasOwnProperty("whiteListSelector")?k.whiteListSelector:k.allowListSelector;
var z=k.hasOwnProperty("blackListSelector")?n(k.blackListSelector):n(k.denyListSelector);if(!x(y))return ORA.Debug.info("allowList selector is invalid - exiting: "+y,"crossDomain-ANA"),t();if(!x(z))return ORA.Debug.info("denyList selector is invalid - exiting: "+z,"crossDomain-ANA"),t();ORA.Debug.debug("binding using allowList:"+y+" denyList: "+z,"crossDomain-ANA");g(y,z,"mousedown",m);g(y,z,"click",m);if((u=e("xd_co_f")||b("xd_co_f"))||k.testSessionId)ORA.Debug.debug("Adding Mutation","crossDomain-ANA"),
ORA.analytics.addMutation("crossDomain",p,3);ORA.Debug.debug("crossDomain Start Init Complete (unblock)","crossDomain-ANA");return t()}catch(C){return ORA.Debug.debug("crossDomain plugin Init Error (unblock)"+C.message,"crossDomain-ANA"),t()}},{blockCollect:!0});ORA.analytics.plugins.crossDomain={};ORA.analytics.plugins.crossDomain.testNode=function(f){return eval(f)};ORA.analytics.plugins.crossDomain.deleteProperty=function(f){delete k[f]};ORA.analytics.plugins.crossDomain.addProperty=function(f,
h){k[f]=h}})();
(function(){var m,d,a,c,b={enable:!0,cookieDays:365,cookieName:"ORAPERSIST",cookieDomain:"",params:"dcsvid infy riid rid customer_id elqCID elq_cid elq_mid product".split(" "),defPrefix:"DCSext",priority:100,useMostRecent:!0,lowerCaseValues:!0},e=new function(){var n=this;n.getQueryParamsMap=function(l,v){var r=ORA.common.extendObject({}),u=[],k=l,x=v||b;try{r=JSON.parse(l)}catch(w){"string"===typeof k&&(k=k.replace(/^[&\?\s]+/i,""),u=k.split("\x26"));for(var f=0,h=u.length;f<h;++f){k=u[f];k=k.split("\x3d");
var t=k[0].toLowerCase();""!==t&&(r[t]=x.lowerCaseValues?decodeURIComponent(k[1].toLowerCase()):decodeURIComponent(k[1]))}}return r};n.getValueOfExistingParam=function(l,v,r,u,k){var x=null,f,h=k||b;l.forEach(function(t,w){if(w.toLowerCase()===r||w.toLowerCase()===v)f=h.lowerCaseValues&&"string"===typeof t?t.toLowerCase():t});f?(x=f,ORA.Debug.debug("Taking current value from QRY: "+r+'\x3d"'+x+'"',"ANA - pp")):null!==u.getParam(r)&&(x=u.getParam(r),ORA.Debug.debug("Taking current value from dcsMsg: "+
r+'\x3d"'+x+'"',"ANA - pp"));x&&ORA.Debug.debug("Param (current value): "+r+'\x3d"'+x+'"',"ANA - pp");return x};n.getParamValue=function(l,v,r,u,k){l=n.getValueOfExistingParam(l,v,r,u);r=n.getQueryParam(k,r);null===l||"undefined"===l||!b.useMostRecent&&null!==r||(r=l);return r};n.getQueryParam=function(l,v){var r=null;l.forEach(function(u,k){k.toLowerCase()===v&&(r=u)});return r};n.applyPreviouslyPersistedParamsValues=function(l,v,r){for(var u="",k=ORA.common.extendObject({}),x=0,f=b.params.length;x<
f;++x){var h=b.params[x],t=h;ORA.Debug.info("Processing param: "+h,"ANA - pp");v[h]=n.getParamValue(l,h,t,r,v);var w=n.getQueryParam(v,h);w&&(ORA.Debug.info("Overriding MSG value with saved value: "+t+'\x3d"'+w+'"',"ANA - pp"),r.setParam(t,w,!0),k[t]=w);(t=n.getQueryParam(l,h)||n.getQueryParam(l,t))&&ORA.common.QueryParamCache.set(h,t)}k.forEach(function(y,z){u=u+"\x26"+z+"\x3d"+encodeURIComponent(y)});return u=u.replace(/^[&\?\s]+/i,"")};n.arrayIndexOf=function(l,v){if(!ORA.analytics.isArray(l))return-1;
if(Array.prototype.indexOf)return l.indexOf(v);for(var r=0,u=l.length;r<u;r++)if(l[r]===v)return r;return-1}},g=function(){this.getCookieDomain=function(){var n="",l=b.cookieDomain;l==location.hostname&&(l="");a&&a.FPCConfig&&a.FPCConfig.domain&&(n=a.FPCConfig.domain);ORA.Debug.debug("sDCSDomain: "+n,"ANA - pp");l&&"."===l.charAt(0)&&(l=l.slice(1));if(b.cookieDomain)return ORA.Debug.debug("PP config domain: "+n,"ANA - pp"),l;if(a&&a.FPCConfig&&!0===a.FPCConfig.autoTLD)return ORA.Debug.debug("Using TLD Domain: "+
ORA.cookieMgr.checkCookieOnDomainAndGetTLDomain(),"ANA - pp"),ORA.cookieMgr.checkCookieOnDomainAndGetTLDomain();if(n)return ORA.Debug.debug("Tag config domain: "+n,"ANA - pp"),n}},p=function(){this.savePersistedParams=function(n,l,v,r){var u=new Date;u.setDate(u.getDate()+r);r=";domain\x3d"+v+";path\x3d/;expires\x3d"+u.toUTCString();v||(r=";path\x3d/;expires\x3d"+u.toUTCString());m(n,l,r)};this.getPersistedParams=function(n){var l=ORA.common.extendObject({});n=d(n);return null===n?l:l=e.getQueryParamsMap(n)}};
var q=new function(){var n=this,l=new g,v=new p;n.ppMutation=function(r){var u=ORA.common.QueryParamCache.getCache(),k=v.getPersistedParams(b.cookieName);ORA.Debug.debug("QRY params: "+JSON.stringify(u),"ANA - pp");r=e.applyPreviouslyPersistedParamsValues(u,k,r);c||(c=l.getCookieDomain(),ORA.Debug.debug("Cookie domain to use: "+c,"ANA - pp"));ORA.Debug.debug("Saving persistent params in cookie: "+b.cookieName+'\x3d"'+r+'"',"ANA - pp");v.savePersistedParams(b.cookieName,r,c,b.cookieDays)};n.ppInit=
function(r,u){var k=r.config;if(k){for(var x in k)k.hasOwnProperty(x)&&(b[x]=k[x]);k=[];x=0;for(var f=b.params.length;x<f;++x)b.params[x]=b.params[x].toLowerCase(),k.push(b.params[x]);b.params=k}ORA.Debug.info("initializing...","ANA - pp");b.enable?b.params&&0!==b.params.length?(ORA.Debug.debug("params to persist: "+b.params.join(", "),"ANA - pp"),m=ORA.analytics.setCookie,d=ORA.analytics.getCookieRaw,a=ORA.analytics.dcsRef,ORA.analytics.addMutation("persistParams",n.ppMutation,3)):ORA.Debug.debug("no persist params defined - will not run",
"ANA - pp"):ORA.Debug.debug("disabled in config - will not run","ANA - pp");b.blockCollect&&u&&u()}};ORA.regPlugin("pp",q.ppInit);ORA.plugins||(ORA.plugins={});ORA.plugins.pp||(ORA.plugins.pp={});ORA.Debug.debug("PP: Plugin initialized","ANA - pp");ORA.plugins.pp.Domain=new g;ORA.plugins.pp.PersistParams=new p;ORA.plugins.pp.OraclePP=q;ORA.plugins.pp.helper=e;ORA.plugins.pp.config=b})();ORA.Debug.debug("PP: Loading Plugin","ANA");
(function(){var m={enable:!1,tagManager:"Google Tag Manager"},d=function(){try{var c=-1!==ORA.analyticsModule.prototype.postload.toString().indexOf("dataLayer")}catch(b){c=!1}c?ORA.Debug.debug("Tag Manager Plugin legacy postLoad found - not adding event","tagMgr"):"undefined"!==typeof window.dataLayer?(window.dataLayer.push({event:"ora.load"}),ORA.Debug.debug("Tag Manager Plugin sending ready event to GTM","tagMgr")):ORA.Debug.debug("Tag Manager Plugin - no GTM dataLayer found","tagMgr")},a=function(c,
b){var e=b||function(){},g=c&&c.config||{};m=ORA.common._shallowMerge(m,g);void 0===g.enable||g.enable?(ORA.analytics.dcsRef.config.s_disableSeed=!0,ORA.common.TrackingPipeline.disableSeed(),ORA.Debug.debug("Tag Manager Plugin disabling seed event","tagMgr"),"Google Tag Manager"===m.tagManager&&ORA.addEventHandler(ORA.Event.ANA_PRODUCT_READY,d,null,!0),e(),ORA.Debug.debug("Tag Manager Plugin init complete","tagMgr")):(ORA.Debug.debug("Tag Manager Plugin is disabled, exiting","tagMgr"),e())};ORA.Debug.debug("Tag Manager - Registering Plugin",
"tagMgr");ORA.regPlugin("tagMgr",a,{blockCollect:!0});ORA.analytics.plugins.tagMgr={};ORA.analytics.plugins.tagMgr.init=a;ORA.analytics.plugins.tagMgr.testNode=function(c){return eval(c)}})();ORA.setExecuteState("analytics","ready");ORA.fireEvent(new ORA.Event(ORA.Event.ANA_LOAD_COMPLETE,ORA.Event.STATUS_SUCCESS),!0);